# kenpom is the key, standard (draftkings) is the value
NAME_REPLACEMENT_DICT = {
    'East Tennessee State': 'ETSU',
    'Army': 'Army West Point',
    'Penn': 'Pennsylvania',
    'Mississippi': 'Ole Miss',
    'Bethune Cookman': 'Bethune-Cookman',
    'Louisiana Monroe': 'ULM',
    'UMKC': 'Kansas City',
    'Grambling State': 'Grambling',
    'SIU Edwardsville': 'SIUE',
    'Incarnate Word': 'UIW',
    'Sam Houston State': 'Sam Houston',
    'UT Rio Grande Valley': 'UTRGV',
    'Saint Mary\'s': 'Saint Marys',
    'Arkansas Pine Bluff': 'Arkansas-Pine Bluff',
    'Loyola MD': 'Loyola Maryland',
    'Southern Miss': 'Southern Mississippi',
    'Louisiana': 'Louisiana-Lafayette',
    'Prairie View A&M': 'Prairie View',
    'Texas A&M Corpus Chris': 'A&M-Corpus Christi',
    'Stephen F. Austin': 'SFA',
    'Central Connecticut': 'Central Connecticut State',
    'State Bonaventure': 'Saint Bonaventure',
    'State Thomas': 'Saint Thomas MN',
    'Alcorn State': 'Alcorn',
    'Florida Gulf Coast': 'FGCU',
    'UNC Wilmington': 'UNCW',
    'Mount State Mary\'s': 'Mount Saint Marys',
    'Southern': 'Southern University',
    'Central Connecticut State': 'North Carolina State',
    'N.C. State': 'North Carolina State',
    'Cal Baptist': 'California Baptist',
    'Gardner Webb': 'Gardner-Webb',
    'State Francis NY': 'Saint Francis Brooklyn',
    'State Francis PA': 'Saint Francis PA',
    'McNeese State': 'McNeese',
    'Cal State Bakersfield': 'CSU Bakersfield',
    'Cal State Northridge': 'CSUN',
    'Tennessee Martin': 'UT Martin',
    'Maryland Eastern Shore': 'UMES',
    'Loyola Marymount': 'LMU',
    'Mississippi Valley State': 'Mississippi Valley',
    'Connecticut': 'UConn',
    'Nebraska Omaha': 'Omaha',
    'Saint Joseph\'s': 'Saint Josephs',
}
